ALTER TABLE admin_users
  ADD COLUMN IF NOT EXISTS theme TEXT NOT NULL DEFAULT 'system',
  ADD COLUMN IF NOT EXISTS avatar_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS thumbnail_key TEXT NOT NULL DEFAULT '';
