CREATE TABLE IF NOT EXISTS words (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kana TEXT NOT NULL,
  kanji TEXT NOT NULL DEFAULT '',
  romaji TEXT NOT NULL DEFAULT '',
  meaning TEXT NOT NULL,
  example TEXT NOT NULL DEFAULT '',
  example_meaning TEXT NOT NULL DEFAULT '',
  level TEXT NOT NULL DEFAULT 'N5',
  sort_order INTEGER NOT NULL DEFAULT 0
);

INSERT INTO words(id, kana, kanji, romaji, meaning, example, example_meaning, level, sort_order) VALUES
  (1, 'わたし', '私', 'watashi', '我', '私は学生です。', '我是学生。', 'N5', 1),
  (2, 'あなた', '', 'anata', '你', 'あなたは先生ですか。', '你是老师吗？', 'N5', 2),
  (3, 'ひと', '人', 'hito', '人', 'あの人は誰ですか。', '那个人是谁？', 'N5', 3),
  (4, 'がくせい', '学生', 'gakusei', '学生', '私は大学の学生です。', '我是大学生。', 'N5', 4),
  (5, 'せんせい', '先生', 'sensei', '老师', '田中先生はやさしいです。', '田中老师很温柔。', 'N5', 5),
  (6, 'ともだち', '友達', 'tomodachi', '朋友', '友達と映画を見ます。', '和朋友看电影。', 'N5', 6),
  (7, 'みず', '水', 'mizu', '水', '水を飲みます。', '喝水。', 'N5', 7),
  (8, 'ほん', '本', 'hon', '书', '本を読みます。', '读书。', 'N5', 8),
  (9, 'がっこう', '学校', 'gakkou', '学校', '学校へ行きます。', '去学校。', 'N5', 9),
  (10, 'いえ', '家', 'ie', '家', '家に帰ります。', '回家。', 'N5', 10),
  (11, 'くるま', '車', 'kuruma', '车', '車で行きます。', '坐车去。', 'N5', 11),
  (12, 'でんしゃ', '電車', 'densha', '电车', '電車に乗ります。', '乘电车。', 'N5', 12),
  (13, 'たべもの', '食べ物', 'tabemono', '食物', '日本の食べ物が好きです。', '喜欢日本的食物。', 'N5', 13),
  (14, 'みせ', '店', 'mise', '店；商店', '店でパンを買います。', '在店里买面包。', 'N5', 14),
  (15, 'じかん', '時間', 'jikan', '时间', '時間がありません。', '没有时间。', 'N5', 15),
  (16, 'きょう', '今日', 'kyou', '今天', '今日は暑いです。', '今天很热。', 'N5', 16),
  (17, 'あした', '明日', 'ashita', '明天', '明日も来ます。', '明天也来。', 'N5', 17),
  (18, 'たべる', '食べる', 'taberu', '吃', 'ご飯を食べる。', '吃饭。', 'N5', 18),
  (19, 'のむ', '飲む', 'nomu', '喝', 'お茶を飲む。', '喝茶。', 'N5', 19),
  (20, 'みる', '見る', 'miru', '看', 'テレビを見る。', '看电视。', 'N5', 20),
  (21, 'いく', '行く', 'iku', '去', '学校へ行く。', '去学校。', 'N5', 21),
  (22, 'くる', '来る', 'kuru', '来', '友達が来る。', '朋友来。', 'N5', 22),
  (23, 'する', '', 'suru', '做', '宿題をする。', '做作业。', 'N5', 23),
  (24, 'かう', '買う', 'kau', '买', '服を買う。', '买衣服。', 'N5', 24),
  (25, 'おおきい', '大きい', 'ookii', '大的', '大きい家です。', '是大房子。', 'N5', 25),
  (26, 'ちいさい', '小さい', 'chiisai', '小的', '小さい犬です。', '是小狗。', 'N5', 26),
  (27, 'たかい', '高い', 'takai', '高的；贵的', 'この本は高いです。', '这本书很贵。', 'N5', 27),
  (28, 'やすい', '安い', 'yasui', '便宜的', 'この店は安いです。', '这家店很便宜。', 'N5', 28),
  (29, 'おいしい', '美味しい', 'oishii', '好吃的', 'ラーメンは美味しいです。', '拉面很好吃。', 'N5', 29),
  (30, 'あたらしい', '新しい', 'atarashii', '新的', '新しい車です。', '是新车。', 'N5', 30)
ON CONFLICT (id) DO UPDATE SET
  kana = EXCLUDED.kana,
  kanji = EXCLUDED.kanji,
  romaji = EXCLUDED.romaji,
  meaning = EXCLUDED.meaning,
  example = EXCLUDED.example,
  example_meaning = EXCLUDED.example_meaning,
  level = EXCLUDED.level,
  sort_order = EXCLUDED.sort_order;

SELECT setval(pg_get_serial_sequence('words', 'id'), COALESCE((SELECT MAX(id) FROM words), 1));
